CREATE TABLE `personalityProfiles` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`avatarId` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`traits` json NOT NULL,
	`backstory` text,
	`occupation` varchar(255),
	`age` int,
	`location` varchar(255),
	`interests` json,
	`conversationStyle` varchar(64) NOT NULL,
	`responseLength` enum('short','medium','long') DEFAULT 'medium',
	`emojiUsage` enum('none','minimal','moderate','frequent') DEFAULT 'moderate',
	`languageStyle` varchar(64),
	`voicePersonality` enum('seductive','playful','professional','sweet','dominant') DEFAULT 'seductive',
	`voiceName` varchar(255),
	`flirtLevel` int DEFAULT 5,
	`nsfwWillingness` int DEFAULT 5,
	`responseSpeed` enum('instant','realistic','slow') DEFAULT 'realistic',
	`isTemplate` boolean DEFAULT false,
	`isPublic` boolean DEFAULT false,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `personalityProfiles_id` PRIMARY KEY(`id`)
);
